# AUTOGENERATED! DO NOT EDIT! File to edit: 02.2-using-a-saved-basic-fastai-model.ipynb.

# %% auto 0
__all__ = ['plt', 'learn', 'categories', 'image', 'label', 'examples', 'intf', 'is_cat', 'classify_images']

# %% 02.2-using-a-saved-basic-fastai-model.ipynb 5
from fastai.vision.all import *
import gradio as gr
import pathlib

# needed because model was trained on windows but runs on linux
plt = platform.system()
if plt != 'Windows': pathlib.WindowsPath = pathlib.PosixPath

def is_cat(x): return x[0].isupper() 

# %% 02.2-using-a-saved-basic-fastai-model.ipynb 9
learn = load_learner('model.pkl')

# %% 02.2-using-a-saved-basic-fastai-model.ipynb 13
categories = ('Dog', 'Cat')

def classify_images(img):
    pred,idx,probs = learn.predict(img)
    return dict(zip(categories, map(float,probs)))

# %% 02.2-using-a-saved-basic-fastai-model.ipynb 16
image = gr.inputs.Image(shape=(192,192))
label = gr.outputs.Label()
examples = ['dog.jpg', 'cat.jpg', 'dunno.jpg']

intf = gr.Interface(fn=classify_images, inputs=image, outputs=label, examples=examples)
intf.launch(inline=False)
